// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunTraceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunTraceRequest) Reset()         { *m = RunTraceRequest{} }
func (m *RunTraceRequest) String() string { return proto.CompactTextString(m) }
func (*RunTraceRequest) ProtoMessage()    {}
func (*RunTraceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *RunTraceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTraceRequest.Unmarshal(m, b)
}
func (m *RunTraceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTraceRequest.Marshal(b, m, deterministic)
}
func (m *RunTraceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTraceRequest.Merge(m, src)
}
func (m *RunTraceRequest) XXX_Size() int {
	return xxx_messageInfo_RunTraceRequest.Size(m)
}
func (m *RunTraceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTraceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunTraceRequest proto.InternalMessageInfo

func (m *RunTraceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunTraceRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type RunTraceResponse struct {
	Syscalls             map[string]int64 `protobuf:"bytes,3,rep,name=syscalls,proto3" json:"syscalls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RunTraceResponse) Reset()         { *m = RunTraceResponse{} }
func (m *RunTraceResponse) String() string { return proto.CompactTextString(m) }
func (*RunTraceResponse) ProtoMessage()    {}
func (*RunTraceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *RunTraceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunTraceResponse.Unmarshal(m, b)
}
func (m *RunTraceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunTraceResponse.Marshal(b, m, deterministic)
}
func (m *RunTraceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunTraceResponse.Merge(m, src)
}
func (m *RunTraceResponse) XXX_Size() int {
	return xxx_messageInfo_RunTraceResponse.Size(m)
}
func (m *RunTraceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunTraceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunTraceResponse proto.InternalMessageInfo

func (m *RunTraceResponse) GetSyscalls() map[string]int64 {
	if m != nil {
		return m.Syscalls
	}
	return nil
}

type SyncProfileRequest struct {
	Profiles             []*SeccompProfile `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SyncProfileRequest) Reset()         { *m = SyncProfileRequest{} }
func (m *SyncProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SyncProfileRequest) ProtoMessage()    {}
func (*SyncProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *SyncProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncProfileRequest.Unmarshal(m, b)
}
func (m *SyncProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncProfileRequest.Marshal(b, m, deterministic)
}
func (m *SyncProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncProfileRequest.Merge(m, src)
}
func (m *SyncProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SyncProfileRequest.Size(m)
}
func (m *SyncProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncProfileRequest proto.InternalMessageInfo

func (m *SyncProfileRequest) GetProfiles() []*SeccompProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type SeccompProfile struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Profile              []byte   `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeccompProfile) Reset()         { *m = SeccompProfile{} }
func (m *SeccompProfile) String() string { return proto.CompactTextString(m) }
func (*SeccompProfile) ProtoMessage()    {}
func (*SeccompProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *SeccompProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeccompProfile.Unmarshal(m, b)
}
func (m *SeccompProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeccompProfile.Marshal(b, m, deterministic)
}
func (m *SeccompProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeccompProfile.Merge(m, src)
}
func (m *SeccompProfile) XXX_Size() int {
	return xxx_messageInfo_SeccompProfile.Size(m)
}
func (m *SeccompProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_SeccompProfile.DiscardUnknown(m)
}

var xxx_messageInfo_SeccompProfile proto.InternalMessageInfo

func (m *SeccompProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SeccompProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SeccompProfile) GetProfile() []byte {
	if m != nil {
		return m.Profile
	}
	return nil
}

type SyncProfileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncProfileResponse) Reset()         { *m = SyncProfileResponse{} }
func (m *SyncProfileResponse) String() string { return proto.CompactTextString(m) }
func (*SyncProfileResponse) ProtoMessage()    {}
func (*SyncProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *SyncProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncProfileResponse.Unmarshal(m, b)
}
func (m *SyncProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncProfileResponse.Marshal(b, m, deterministic)
}
func (m *SyncProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncProfileResponse.Merge(m, src)
}
func (m *SyncProfileResponse) XXX_Size() int {
	return xxx_messageInfo_SyncProfileResponse.Size(m)
}
func (m *SyncProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncProfileResponse proto.InternalMessageInfo

func (m *SyncProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SyncProfileResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RunTraceRequest)(nil), "agent.RunTraceRequest")
	proto.RegisterType((*RunTraceResponse)(nil), "agent.RunTraceResponse")
	proto.RegisterMapType((map[string]int64)(nil), "agent.RunTraceResponse.SyscallsEntry")
	proto.RegisterType((*SyncProfileRequest)(nil), "agent.SyncProfileRequest")
	proto.RegisterType((*SeccompProfile)(nil), "agent.SeccompProfile")
	proto.RegisterType((*SyncProfileResponse)(nil), "agent.SyncProfileResponse")
}

func init() {
	proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77)
}

var fileDescriptor_56ede974c0020f77 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x5f, 0x4f, 0x83, 0x30,
	0x14, 0xc5, 0x2d, 0x38, 0xc7, 0xee, 0x74, 0x2e, 0xd7, 0x7f, 0x95, 0x27, 0x42, 0x62, 0xc2, 0xd3,
	0xa2, 0xf3, 0xc5, 0x68, 0x8c, 0xd9, 0xc3, 0xf4, 0xcd, 0x98, 0xce, 0x2f, 0x80, 0x5d, 0x35, 0x44,
	0xd6, 0x62, 0x0b, 0x26, 0x7c, 0x0b, 0xe3, 0x27, 0x36, 0x83, 0x82, 0xce, 0xe9, 0x5b, 0x0f, 0xf7,
	0xf4, 0xf0, 0xbb, 0x27, 0x85, 0x7e, 0xfc, 0x22, 0x64, 0x3e, 0xca, 0xb4, 0xca, 0x15, 0x76, 0x2a,
	0x11, 0x5e, 0xc3, 0x2e, 0x2b, 0xe4, 0xa3, 0x8e, 0xb9, 0x60, 0xe2, 0xad, 0x10, 0x26, 0xc7, 0x01,
	0x38, 0xc9, 0x9c, 0x92, 0x80, 0x44, 0x3d, 0xe6, 0x24, 0x73, 0xf4, 0xc1, 0x9b, 0x17, 0x3a, 0xce,
	0x13, 0x25, 0xa9, 0x13, 0x90, 0xc8, 0x65, 0xad, 0x0e, 0x3f, 0x09, 0x0c, 0xbf, 0xef, 0x9b, 0x4c,
	0x49, 0x23, 0x70, 0x02, 0x9e, 0x29, 0x0d, 0x8f, 0xd3, 0xd4, 0x50, 0x37, 0x70, 0xa3, 0xfe, 0xf8,
	0x64, 0x54, 0xff, 0xfa, 0xb7, 0x75, 0x34, 0xb3, 0xbe, 0xa9, 0xcc, 0x75, 0xc9, 0xda, 0x6b, 0xfe,
	0x15, 0xec, 0xac, 0x8c, 0x70, 0x08, 0xee, 0xab, 0x28, 0x2d, 0xd5, 0xf2, 0x88, 0xfb, 0xd0, 0x79,
	0x8f, 0xd3, 0x42, 0x58, 0xa6, 0x5a, 0x5c, 0x3a, 0x17, 0x24, 0xbc, 0x03, 0x9c, 0x95, 0x92, 0x3f,
	0x68, 0xf5, 0x9c, 0xa4, 0xed, 0x5a, 0x67, 0xe0, 0x65, 0xf5, 0x17, 0x43, 0x9d, 0x8a, 0xea, 0xc0,
	0x52, 0xcd, 0x04, 0xe7, 0x6a, 0x91, 0x35, 0xfe, 0xd6, 0x16, 0xde, 0xc3, 0x60, 0x75, 0xb6, 0xd6,
	0x0d, 0xc2, 0xa6, 0x8c, 0x17, 0x35, 0x43, 0x8f, 0x55, 0x67, 0xa4, 0xd0, 0xb5, 0x09, 0xd4, 0x0d,
	0x48, 0xb4, 0xcd, 0x1a, 0x19, 0x4e, 0x61, 0x6f, 0x05, 0xcc, 0xf6, 0x45, 0xa1, 0x6b, 0x0a, 0xce,
	0x85, 0x31, 0x55, 0xb2, 0xc7, 0x1a, 0xb9, 0xdc, 0x51, 0x68, 0xad, 0xb4, 0xcd, 0xaf, 0xc5, 0xf8,
	0x83, 0x40, 0x67, 0xb2, 0x24, 0xc7, 0x1b, 0xf0, 0x9a, 0x4a, 0xf1, 0x70, 0xad, 0xe3, 0x6a, 0x6f,
	0xff, 0xe8, 0x9f, 0xee, 0xc3, 0x8d, 0x53, 0x82, 0xb7, 0xd0, 0xff, 0x41, 0x84, 0xc7, 0x4d, 0x23,
	0x6b, 0xf5, 0xf9, 0xfe, 0x5f, 0xa3, 0x26, 0xe9, 0x69, 0xab, 0x7a, 0x54, 0xe7, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf1, 0x97, 0x2a, 0x93, 0x63, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	RunTrace(ctx context.Context, in *RunTraceRequest, opts ...grpc.CallOption) (Agent_RunTraceClient, error)
	SyncProfile(ctx context.Context, in *SyncProfileRequest, opts ...grpc.CallOption) (*SyncProfileResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) RunTrace(ctx context.Context, in *RunTraceRequest, opts ...grpc.CallOption) (Agent_RunTraceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Agent_serviceDesc.Streams[0], "/agent.Agent/RunTrace", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentRunTraceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Agent_RunTraceClient interface {
	Recv() (*RunTraceResponse, error)
	grpc.ClientStream
}

type agentRunTraceClient struct {
	grpc.ClientStream
}

func (x *agentRunTraceClient) Recv() (*RunTraceResponse, error) {
	m := new(RunTraceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentClient) SyncProfile(ctx context.Context, in *SyncProfileRequest, opts ...grpc.CallOption) (*SyncProfileResponse, error) {
	out := new(SyncProfileResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/SyncProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	RunTrace(*RunTraceRequest, Agent_RunTraceServer) error
	SyncProfile(context.Context, *SyncProfileRequest) (*SyncProfileResponse, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) RunTrace(req *RunTraceRequest, srv Agent_RunTraceServer) error {
	return status.Errorf(codes.Unimplemented, "method RunTrace not implemented")
}
func (*UnimplementedAgentServer) SyncProfile(ctx context.Context, req *SyncProfileRequest) (*SyncProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncProfile not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_RunTrace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunTraceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).RunTrace(m, &agentRunTraceServer{stream})
}

type Agent_RunTraceServer interface {
	Send(*RunTraceResponse) error
	grpc.ServerStream
}

type agentRunTraceServer struct {
	grpc.ServerStream
}

func (x *agentRunTraceServer) Send(m *RunTraceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Agent_SyncProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SyncProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/SyncProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SyncProfile(ctx, req.(*SyncProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncProfile",
			Handler:    _Agent_SyncProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunTrace",
			Handler:       _Agent_RunTrace_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
